site_name: andjmp

theme:
  name: material
  favicon: images/favicon.svg
  logo: images/andjmp.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: auto
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    # - navigation.indexes
    - navigation.expand
extra_css:
  - stylesheets/extra.css

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andjmp
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/notandjmp

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - meta
  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Blog:
    - 2022:
      - July:
          - blog/1.md